## Process this file with automake to generate Makefile.in.
## 19990904 mortene.

## Sources and installation headers.

PublicHeaders = \
	SoX3D.h \
	SoX3DAnchor.h \
	SoX3DAppearance.h \
	SoX3DAudioClip.h \
	SoX3DBackground.h \
	SoX3DBillboard.h \
	SoX3DBox.h \
	SoX3DCollision.h \
	SoX3DColor.h \
	SoX3DColorInterpolator.h \
	SoX3DCone.h \
	SoX3DCoordinate.h \
	SoX3DCoordinateInterpolator.h \
	SoX3DCylinder.h \
	SoX3DCylinderSensor.h \
	SoX3DDirectionalLight.h \
	SoX3DDragSensor.h \
	SoX3DElevationGrid.h \
	SoX3DExtrusion.h \
	SoX3DFog.h \
	SoX3DFontStyle.h \
	SoX3DGeometry.h \
	SoX3DGroup.h \
	SoX3DImageTexture.h \
	SoX3DIndexedFaceSet.h \
	SoX3DIndexedLine.h \
	SoX3DIndexedLineSet.h \
	SoX3DIndexedShape.h \
	SoX3DInline.h \
	SoX3DInterpolator.h \
	SoX3DLOD.h \
	SoX3DLight.h \
	SoX3DMacros.h \
	SoX3DMaterial.h \
	SoX3DMovieTexture.h \
	SoX3DNavigationInfo.h \
	SoX3DNodes.h \
	SoX3DNormal.h \
	SoX3DNormalInterpolator.h \
	SoX3DOrientationInterpolator.h \
	SoX3DParent.h \
	SoX3DPixelTexture.h \
	SoX3DPlaneSensor.h \
	SoX3DPointLight.h \
	SoX3DPointSet.h \
	SoX3DPositionInterpolator.h \
	SoX3DProximitySensor.h \
	SoX3DScalarInterpolator.h \
	SoX3DScript.h \
	SoX3DSensor.h \
	SoX3DShape.h \
	SoX3DSound.h \
	SoX3DSphere.h \
	SoX3DSphereSensor.h \
	SoX3DSpotLight.h \
	SoX3DSubInterpolator.h \
	SoX3DSwitch.h \
	SoX3DText.h \
	SoX3DTexture.h \
	SoX3DTextureCoordinate.h \
	SoX3DTextureTransform.h \
	SoX3DTimeSensor.h \
	SoX3DTouchSensor.h \
	SoX3DTransform.h \
	SoX3DVertexLine.h \
	SoX3DVertexPoint.h \
	SoX3DVertexShape.h \
	SoX3DViewpoint.h \
	SoX3DVisibilitySensor.h \
	SoX3DWorldInfo.h
PrivateHeaders =
ObsoleteHeaders =

##$ BEGIN TEMPLATE Make-Include-Common(X3Dnodes, X3Dnodes)
# **************************************************************************
# This template depends on the following variables having been set up before
# its invokation.
#
# PublicHeaders    - header files that should be installed
# PrivateHeaders   - source files that should be distributed, but not
#                    installed - including source-included source files.
# ObsoletedHeaders - header files that should be removed upon installation

# Everything below is autogenerated from a macro, so don't modify
# within the Makefile.am itself. 19991201 mortene.

EXTRA_DIST = $(PrivateHeaders)

if MAC_FRAMEWORK
libX3Dnodesincdir = $(MAC_FRAMEWORK_PREFIX)/$(MAC_FRAMEWORK_NAME).framework/Versions/$(MAC_FRAMEWORK_VERSION)/Headers/X3Dnodes
# hack to change libdir value when installing Mac OS X compiler framework
lib@nop@dir = $(MAC_FRAMEWORK_PREFIX)/$(MAC_FRAMEWORK_NAME).framework/Versions/$(MAC_FRAMEWORK_VERSION)/Libraries
else
libX3Dnodesincdir = $(includedir)/Inventor/X3Dnodes
endif
libX3Dnodesinc_HEADERS = $(PublicHeaders)

install-libX3DnodesincHEADERS: $(libX3Dnodesinc_HEADERS)
	@$(NORMAL_INSTALL)
	@if test x"$(libX3Dnodesinc_HEADERS)" = x""; then :; else \
	  echo " $(mkinstalldirs) $(DESTDIR)$(libX3Dnodesincdir)"; \
	  $(mkinstalldirs) $(DESTDIR)$(libX3Dnodesincdir); \
	fi
	@list='$(libX3Dnodesinc_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  src="$$d$$p"; dst="$(DESTDIR)$(libX3Dnodesincdir)/$$f"; \
	  if cmp -s "$$src" "$$dst"; then :; else \
	    echo " $(INSTALL_HEADER) $$src $$dst"; \
	    $(INSTALL_HEADER) "$$src" "$$dst" || exit 1; \
	  fi \
	done
	@list='$(ObsoletedHeaders)'; for f in $$list; do \
	  file="$(DESTDIR)$(libX3Dnodesincdir)/$$f"; \
	  if test -x "$$file"; then \
	    echo " rm -f $$file"; \
	    rm -f "$$file"; \
	  fi \
	done; \
	:

##$ END TEMPLATE Make-Include-Common
